	CREATE TABLE DOKTER
	 (
	 KD_DOK CHAR(4) PRIMARY KEY,
	 NM_DOK VARCHAR(50) NOT NULL,
	 ALMT_DOK  VARCHAR(50) NOT NULL,
	 JKEL_DOK CHAR(1),
	 SPESIAL_DOK VARCHAR(30) NOT NULL,
	 DARAH_DOK CHAR(2),
	 LHR_DOK DATE
	 );
	 
	 CREATE TABLE PASIEN
	 (
	 KD_PAS CHAR(4) PRIMARY KEY,
	 NM_PAS VARCHAR(50) NOT NULL,
	 ALMT_PAS VARCHAR(50) NOT NULL,
	 JKEL_PAS CHAR(1),
	 DARAH_PAS CHAR(2),
	 LHR_PAS DATE,
	 TGL_DAFTAR DATE NOT NULL,
	 );
	 
	 CREATE TABLE OBAT
	 (
	 KD_OBAT CHAR(4) PRIMARY KEY,
	 NM_OBAT VARCHAR(50) NOT NULL,
	 STOK_OBAT NUMERIC(7),
	 HRG_OBAT NUMERIC(7),
	 SATUAN VARCHAR(20),
	 );
	 
	 
	 CREATE TABLE RESEP
	 (
	 NO_RESEP CHAR(4) PRIMARY KEY,
	 KD_PAS CHAR (4),
	 KD_DOK CHAR (4),
	 KD_OBAT CHAR(4),
	 TGL_RESEP DATE,
	 JML_BELI NUMERIC(7) NOT NULL,
	 FOREIGN KEY (KD_PAS) REFERENCES PASIEN(KD_PAS),
	 FOREIGN KEY (KD_DOK) REFERENCES DOKTER(KD_DOK),
	 FOREIGN KEY (KD_OBAT) REFERENCES OBAT(KD_OBAT)
	 );
	 
	 
	 CREATE TABLE PENANGANAN
	 (
	 KD_DOK CHAR(4),
	 KD_PAS CHAR(4),
	 TGL_PERIKSA DATE,
	 DIAGNOSA VARCHAR(1000),
	 PRIMARY KEY (KD_DOK,KD_PAS),
	 FOREIGN KEY (KD_DOK) REFERENCES DOKTER(KD_DOK),
	 FOREIGN KEY (KD_PAS) REFERENCES PASIEN(KD_PAS)
	 );
	 
	 CREATE TABLE promo 
	 (
	 kd_promo CHAR(4) not null, 
	 kd_obat CHAR(4) not null,
	 nm_promo VARCHAR(25) null, 
	 tgl_promo DATE null
	 );
